### PR TITLE
Rewrote classes for author fix

### LINKED ISSUE #9: Missing author metrics in SonarQube
- `vcsparser_numauthors10perc_1y`
- `vcsparser_numauthors10perc_6m`
- `vcsparser_numauthors10perc_3m`
- `vcsparser_numauthors10perc_30d`

image

### PR DESCRIPTION
**Pull request by roryclaasen**
fixes #9 

Compute NumAuthors Metric now will no longer try and calculate if an author is over the threshold on a project level but rather count if a (unique) author is over the threshold per file.

Map syntax syntax
[project key][[time period](https://github.com/roryclaasen/sonar-vcsparser-plugin/blob/master/src/main/java/dev/roryclaasen/vcsparser/metrics/MetricDate.java)][component key][author name] = over threshold.

### CODE REVIEW

File: src/main/java/dev/roryclaasen/vcsparser/measures/ComputeNumAuthorsMetric.java [hunk 1]
```diff
@@ -22,17 +24,19 @@
...
-	private String[] numChanges = getAllDatesForMetric("vcsparser_numchanges");
+	private String numChanges = "vcsparser_numchanges";
 
-	private String[] numAuthors = PluginMetric.NUM_AUTHORS.getKeyAllDates();
-	private String[] numAuthors10Perc = PluginMetric.NUM_AUTHORS_10_PERC.getKeyAllDates();
+	private PluginMetric numAuthors = PluginMetric.NUM_AUTHORS;
+	private PluginMetric numAuthors10Perc = PluginMetric.NUM_AUTHORS_10_PERC;
 
-	protected static Map<String, Map<String, List<AuthorData>>> authorsCache = new HashMap<String, Map<String, List<AuthorData>>>();
+	// authorsCache[project][date][file][author] = over10perc
```
Comment (ericlemes) [inline src/main/java/dev/roryclaasen/vcsparser/measures/ComputeNumAuthorsMetric.java]: Please remove commented line.

File: src/main/java/dev/roryclaasen/vcsparser/measures/ComputeNumAuthorsMetric.java [hunk 2]
```diff
@@ -49,59 +53,92 @@ public void removeProjectCache(String projectKey) {
 			authorsCache.remove(projectKey);
 	}
 
+	protected void saveProjectCache(String projectKey, MetricDate date, String currentKey, Map<String, Boolean> authorMap) {
+		// Project (projectKey)
+		if (!authorsCache.containsKey(projectKey))
```
Comment (ericlemes) [inline src/main/java/dev/roryclaasen/vcsparser/measures/ComputeNumAuthorsMetric.java:57]: I'm quite curious. Do you really need to index by projectKey? I thought you could never have 2 projects running at the same time at sonar. Perhaps only on commercial editions.

**Review by ericlemes — APPROVED** [review]
Some minor tweaks. Everything else seems good. I'm glad you spotted the issue with the way you were computing before.

File: src/main/java/dev/roryclaasen/vcsparser/measures/ComputeNumAuthorsMetric.java (hunk 2 above)
Comment (roryclaasen) [reply src/main/java/dev/roryclaasen/vcsparser/measures/ComputeNumAuthorsMetric.java:57]: I believe you can have more than one worker, however the reason is more due to the fact that post analysis the map needs to be cleaned so that there is no left over data ([`PostProjectAnalysisHook.java`](https://github.com/roryclaasen/sonar-vcsparser-plugin/tree/master/src/main/java/dev/roryclaasen/vcsparser)). I thought by indexing under project key would be easier as I am able to remove all in one call later on.

> #### Speed up your analysis by adding more Workers
> Increase the number of Compute Engine Workers with the Enterprise Edition.
>
> [Learn More](https://redirect.sonarsource.com/editions/enterprise.html)
